### ISSUE TITLE
apt gives warning when running xetch on Ubuntu

### ISSUE THREAD

**Issue by robtech21** [B00bleaTea/xetch#6]
I was testing xetch on repl.it (the command line runs on Ubuntu 18.04) so I could test the fixes I did and it gave me the following error:

`WARNING: APT does not have a stable CLI interface. Use with caution in scripts.`

![Screenshot 2021-03-18 at 8 56 44 AM](https://user-images.githubusercontent.com/77758464/111631184-7d949d80-87c9-11eb-9768-eba3ff309de5.png)

Does anyone know of a way to suppress that warning?

**Comment by robtech21** [comment]
In addition, the Ubuntu logo seems kind of off...

**Comment by ar1ja** [comment]
sorry to hear that, i can fix the logo, but I'm still looking fir a way to stop this from happening, I'll do a lot of searching today, I'll be out with a working update in  1-2 days hopefully

**Comment by robtech21** [comment]
> sorry to hear that, i can fix the logo, but I'm still looking fir a way to stop this from happening, I'll do a lot of searching today, I'll be out with a working update in 1-2 days hopefully

Okay, thank you! If I have time I'll do some research and submit a pull request if I can get it fixed before you.

**Comment by ar1ja** [comment]
heya, update,
i tried multiple methods to do it, including disabling stderr,
none of them worked.
i found out that it's okay for this issue to be there and it's nothing to be worried about, though i will still be looking into it
https://askubuntu.com/questions/990823/apt-gives-unstable-cli-interface-warning
https://github.com/microsoft/azure-pipelines-agent/issues/2304
https://itectec.com/ubuntu/ubuntu-apt-gives-unstable-cli-interface-warning/

**Comment by ar1ja** [comment]
hey, last update,
I'm unable to fix this issue as it's there by default,
I'll try fixing this issue, but for now I'll close this issue:)

**Comment by Picoseconds** [comment]
You need to use apt-get though

**Comment by ar1ja** [comment]
> You need to use apt-get though

the script lists all packages, apt-get can't do that, i just used dpkg:)

**Comment by Picoseconds** [comment]
I'm Lightbulb and I told you to use dpkg
